//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExerciseOnData.DataModel
{
    using System;
    
    [Flags]
    public enum TeachersCourse : int
    {
        Csharp = 1,
        Java = 2,
        html = 4,
        Css = 8,
        pyton = 16
    }
}
